alphabet = 'abcdefg'
print(alphabet[:])
print(alphabet[::-1])
print(alphabet[::2])
print(alphabet[1::2])
print(alphabet[:1])
print(alphabet[len(alphabet) - 1:: len(alphabet) - 2])
print(alphabet[3:4])
print(alphabet[len(alphabet) - 3:])
print(alphabet[3:5])
print(alphabet[3:5][::-1])
